# Generated by Django 6.0.5 on 2026-06-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eiendomsverdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgnr', models.CharField(db_index=True, max_length=9)),
                ('aar', models.CharField(max_length=4)),
                ('tomter_bygninger', models.BigIntegerField(blank=True, null=True)),
                ('sum_varige_driftsmidler', models.BigIntegerField(blank=True, null=True)),
                ('hentet', models.DateField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('orgnr', 'aar'), name='unik_orgnr_aar')],
            },
        ),
    ]
