# Generated by Django 6.0.5 on 2026-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsjektSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilde', models.CharField(max_length=50)),
                ('kommune', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=80)),
                ('referanse', models.CharField(max_length=50)),
                ('tittel', models.CharField(max_length=300)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('dato', models.DateField(blank=True, null=True)),
                ('lenke', models.URLField(blank=True, max_length=300)),
                ('oppdaget', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Prosjektsignaler',
                'constraints': [models.UniqueConstraint(fields=('kilde', 'referanse'), name='unik_kilde_referanse')],
            },
        ),
    ]
