# Generated by Django 6.0.5 on 2026-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_prosjektsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosjektsignal',
            name='part',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
