# Generated by Django 6.0.5 on 2026-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_prosjektsignal_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosjektsignal',
            name='matrikkel',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
