# Generated by Django 6.0.5 on 2026-06-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_prosjektsignal_matrikkel'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosjektsignal',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prosjektsignal',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
