# Generated by Django 6.0.5 on 2026-06-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_prosjektsignal_lat_prosjektsignal_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosjektsignal',
            name='matrikkel',
            field=models.CharField(blank=True),
        ),
    ]
