# Generated by Django 6.0.5 on 2026-06-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_prosjektsignal_matrikkel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosjektsignal',
            name='referanse',
            field=models.CharField(max_length=200),
        ),
    ]
