# Generated by Django 6.0.5 on 2026-06-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_prosjektsignal_referanse'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosjektsignal',
            name='frist',
            field=models.DateField(blank=True, null=True),
        ),
    ]
