# Generated by Django 6.0.5 on 2026-06-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_prosjektsignal_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosjektsignal',
            name='referanse',
            field=models.CharField(max_length=600),
        ),
    ]
