# Generated by Django 6.0.5 on 2026-06-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_prosjektsignal_referanse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosjektsignal',
            name='part',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='prosjektsignal',
            name='referanse',
            field=models.CharField(max_length=200),
        ),
    ]
