# Generated by Django 6.0.5 on 2026-06-10 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_prosjektsignal_part_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('opprettet', models.DateTimeField(auto_now_add=True)),
                ('bruker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentar', to='main.prosjektsignal')),
            ],
        ),
        migrations.CreateModel(
            name='SignalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avvist', models.BooleanField(default=False)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prosjektsignal')),
            ],
            options={
                'unique_together': {('bruker', 'signal')},
            },
        ),
    ]
