# Generated by Django 6.0.5 on 2026-06-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_kommentar_signalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selskap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgnr', models.CharField(db_index=True, max_length=9, unique=True)),
                ('navn', models.CharField(max_length=255)),
                ('kommune', models.CharField(blank=True, max_length=100)),
                ('kommunenummer', models.CharField(blank=True, db_index=True, max_length=4)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('leder', models.CharField(blank=True, max_length=255)),
                ('hjemmeside', models.CharField(blank=True, max_length=255)),
                ('aar', models.CharField(blank=True, max_length=4)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('oppdatert', models.DateField(auto_now=True)),
            ],
        ),
    ]
