# Generated by Django 6.0.5 on 2026-06-15 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_selskap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prosjektsignal',
            name='avvist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prosjektsignal',
            name='avvist_av',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avviste_signaler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prosjektsignal',
            name='avvist_tid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
