# Generated by Django 6.0.5 on 2026-06-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_prosjektsignal_avvist_prosjektsignal_avvist_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosjektsignal',
            name='tittel',
            field=models.CharField(max_length=500),
        ),
    ]
