# Generated by Django 6.0.5 on 2026-06-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_prosjektsignal_tittel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosjektsignal',
            name='lenke',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
